config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'movies#index'

  resources :movies
  resources :directors, only: [:index, :show]

  get 'statistics', to: 'statistics#show'
  get 'results', to: 'searches#results'
  post 'add/:imdb_id', to: 'movies#add', as: :add_to_database

  # Replaced these with "resources :movies"
  # get 'movies', to: 'movies#index', as: :movies
  # get 'movies/:id', to: 'movies#show', as: :movie
  # get 'movies/new', to: 'movies#new', as: :new_movie
  # get 'movies/:id/edit', to: 'movies#edit', as: :edit_movie
  # post 'movies', to: 'movies#create'
  # patch 'movies/:id', to: 'movies#update'
  # delete 'movies/:id', to: 'movies#destroy'

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  skip_before_action :authenticate_user!, only: [:results]

  def results
    query = params[:query]
    response = HTTParty.get("http://www.omdbapi.com/?s=#{query}&type=movie")
    data = JSON.parse(response.body)

    @movies = []
    data['Search'].each do |movie_result|
      new_movie = Movie.new(title: movie_result['Title'],
                           poster: movie_result['Poster'],
                           date: Date.new(movie_result['Year'].to_i))

      new_movie.imdb_id = movie_result['imdbID']

      @movies << new_movie
    end
  end
end

app/views/searches/results.html.haml
.row
  - @movies.each do |movie|
    .col-md-4
      .movie.movie_searches
        .poster= image_tag movie.poster
        .details
          .title
            = movie.title
            = movie.date.try(:year)
          .buttons
            -# Generally would be a POST request, but the Javascript intercepts it.
            = link_to add_to_database_path(movie.imdb_id), class: 'btn btn-primary add_movie' do
              = image_tag 'loading.gif', class: 'loading'
              .glyph_add= fa_icon('plus')
              .glyph_confirmed= fa_icon('check')
              .glyph_error= fa_icon('exclamation')