config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'movies#index'

  resources :movies
  resources :directors, only: [:index, :show]

  get 'statistics', to: 'statistics#show'
  get 'results', to: 'searches#results'
  post 'add/:imdb_id', to: 'movies#add', as: :add_to_database

  # Replaced these with "resources :movies"
  # get 'movies', to: 'movies#index', as: :movies
  # get 'movies/:id', to: 'movies#show', as: :movie
  # get 'movies/new', to: 'movies#new', as: :new_movie
  # get 'movies/:id/edit', to: 'movies#edit', as: :edit_movie
  # post 'movies', to: 'movies#create'
  # patch 'movies/:id', to: 'movies#update'
  # delete 'movies/:id', to: 'movies#destroy'

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title MovieTracker
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'https://www.gstatic.com/charts/loader.js'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    -# Header
    %nav.navbar.navbar-toggleable-md.navbar-light.bg-faded
      %button.navbar-toggler.navbar-toggler-right
        %span.navbar-toggler-icon
      = link_to 'MovieTracker', root_path, class: 'navbar-brand'

      .collapse.navbar-collapse#navbarSupportedContent
        %ul.navbar-nav.mr-auto
          - if signed_in?
            %li.nav-item
              = link_to 'My Movies', movies_path, class: 'nav-link'
            %li.nav-item
              = link_to 'Directors', directors_path, class: 'nav-link'
            %li.nav-item
              = link_to 'Statistics', statistics_path, class: 'nav-link'
            %li.nav-item
              = link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link'

        = form_tag '/results', method: :get, class: 'form-inline my-2 my-lg-0' do
          = text_field_tag :query, '', placeholder: 'Search for a movie', class: 'form-control mr-sm-2'
          = submit_tag 'Search', class: 'btn btn-outline-success my-2 my-sm-0'

    -# Body
    .container

      - if notice
        = notice
      - if alert
        = alert

      = yield

    -# Footer